= The C and String Extension Libraries (cx and sx)
:source-language: c
:source-highlighter: rouge
:rouge-style: custom
:section-refsig: ยง
:icons: font
:text-align: justify
:notitle: true
:!show-link-uri:
:tabsize: 4
:data-uri:
:experimental:
:xrefstyle: basic
:hyphens: en_us
:toc: macro
:toclevels: 3
:toc-title: Contents
:sectnumlevels: 4

toc::[]

== The C Extension Library (cx)

=== The `vec` Types

A `vec` is a dynamically sized vector of owned `void*` pointers. A `vec_int`
is a vector of ``int``s. And a `vec_str` is a wrapper for `vec` that
holds a vector of ownedd ``char*``s.

==== Create

----
vec vec_alloc(vec_alloc_args args);
vec vec_str_alloc(vec_alloc_args args);
vec vec_str_alloc_split(const char* s, const char* sep);
vec_int vec_int_alloc();
vec_int vec_int_alloc_cap(size_t cap);
----

Each of these creates a vector with the default capacity
`VEC_INITIAL_CAP` (`32`), or with the capacity specified by `.cap` (or
`cap` in the `vec_int` case). For `vec_alloc()` the user must
additionally specify the functions `.cmp` for comparing values, `.cpy`
to copy a value, and `.destroy` to free a value.

==== Destroy

----
void vec_free(vec* v);
void vec_str_free(vec* v);
void vec_int_free(vec_int* v);
----

Once a vector is finished with it _must_ be freed using the appropriate
one of these functions. (Like many of the `vec_str` functions,
`vec_str_free()` is just a `#define` alias for `vec_free()`).

==== Functions

== The String Extension Library (sx)
